name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'
      deploy:
        description: 'Deploy the application'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --force

      - name: Build application
        run: npm run build  # This will run your "ng build" command

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/  # Ensure this matches your build output folder

  deploy:
    needs: build  # Ensures deploy runs only after the build job completes successfully
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'yes'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist/  # Ensure this matches the upload path

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI and gh-pages package
        run: |
          npm install -g @angular/cli
          npm install angular-cli-ghpages --save-dev  # Ensure angular-cli-ghpages is installed

      - name: Deploy application
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
